# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"

  # ESTA CONFIGURAÇÃO É EXCLUSIVA DO CONTROL_NOME, NFS SERVE PARA SINCRONIZAR AUTOMATICAMENTE ARQUIVOS NO HOST
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/" 

  config.vm.provision "shell", path: "provission.sh"
  config.vbguest.auto_update = false
  
end
